### ISSUE TITLE
Fix pyproj legacy

### ISSUE THREAD

**Issue by havardhhaugen** [metno/bris-inference#18]

**Comment by ways** [comment]
Wasn't this fixed by #23?

**Comment by ways** [comment]
> Wasn't this fixed by [#23](https://github.com/metno/bris-inference/issues/23)?

No, I see we still have legacy, https://github.com/metno/bris-inference/blob/main/bris/model.py#L41

**Comment by havardhhaugen** [comment]
> Wasn't this fixed by [#23](https://github.com/metno/bris-inference/issues/23)?

#23 should remove any legacy dependencies from dataset/datamodule, but I think it still exists in model, maybe @einrone can look into this?

**Comment by einrone** [comment]
I can take a look and fix it😊
